"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const G = require("../coach/gen-cards.js");

const AKALI = {
  id: "ven-038-166", public_code: "VEN-038/166", name: "Akali, Silent",
  set_id: "VEN", collector_number: 38, rarity: "rare", domains: ["Calm"],
  type: "Unit", stats: { energy: 4, might: 4, power: 1 }, keywords: [],
  description: "I can't be chosen by enemy spells and abilities unless I'm in combat.",
  image: "https://example.invalid/a.png",
};

test("a card's data becomes a compilable CardDef", () => {
  const src = G.generate(AKALI, 900);
  assert.match(src, /class AkaliSilent : public UnitCard/);
  assert.match(src, /d\.id = 900;/);
  assert.match(src, /d\.def_id = R"RB\(ven-038-166\)RB";/);
  assert.match(src, /d\.energy_cost = 4;/);
  assert.match(src, /d\.power_cost = 1;/);
  assert.match(src, /d\.might = 4;/);
  assert.match(src, /d\.domains = \{Domain::Calm\};/);
  assert.match(src, /d\.rarity = Rarity::Rare;/);
  assert.match(src, /void register_card_900\(CardRegistry& r\)/);
});

/* The generated file must say what it is. A stub that looks like an
 * implementation is how a search ends up confidently wrong. */
test("a card with printed text is marked as needing one", () => {
  assert.match(G.generate(AKALI, 900), /needs an implementation/);
  assert.match(G.generate(AKALI, 900), /fidelity\.js blocks any search/);
});

test("a vanilla card says its data is its behaviour", () => {
  const src = G.generate({ ...AKALI, description: "" }, 901);
  assert.match(src, /vanilla: its data IS its behaviour/);
  assert.doesNotMatch(src, /needs an implementation/);
});

/* Keywords are declarative and engine-handled, so declaring them is free
 * behaviour — the one part of a card this generator really does implement. */
test("engine keywords are declared, unknown ones are not invented", () => {
  const src = G.generate(
    { ...AKALI, description: "[Deflect 2] (reminder)[Empower] 2 Fury[Assault 3]" },
    902
  );
  assert.match(src, /d\.keywords\.set\(Keyword::Deflect\);/);
  assert.match(src, /d\.keywords\.set\(Keyword::Assault\);/);
  assert.doesNotMatch(src, /Keyword::Empower/, "Empower is not an engine keyword");
  assert.match(src, /d\.deflect_value = 2;/);
  assert.match(src, /d\.assault_value = 3;/);
});

test("a keyword with no rider defaults to 1", () => {
  assert.equal(G.keywordValue("[Shield] (reminder)", "Shield"), 1);
  assert.equal(G.keywordValue("[Shield 4]", "Shield"), 4);
  assert.equal(G.keywordValue("nothing here", "Shield"), 0);
});

test("names become legal identifiers and stable filenames", () => {
  assert.equal(G.className("Akali, Silent"), "AkaliSilent");
  assert.equal(G.className("B.F. Sword"), "BFSword");
  assert.equal(G.fileStem({ collector_number: 38, name: "Akali, Silent" }), "0038_akali_silent");
});

/* Card ids are the registry's keys. A collision silently replaces a card. */
test("the id scan finds the engine's highest in use", () => {
  let max;
  try { max = G.highestId(process.env.ALPHARUNE_ROOT || "../chorlick/alpharune"); }
  catch (_) { return; }
  assert.ok(max > 700, `expected a populated registry, saw ${max}`);
});

/* Idempotence. The first version took "highest id + 1" for every card, so a
 * second run renumbered all 197 files while the aggregator still called the
 * old ids. That does not link, and the error is nowhere near the cause. */
test("a card the engine already has keeps its id", () => {
  const root = process.env.ALPHARUNE_ROOT || "../chorlick/alpharune";
  let scan;
  try { scan = G.scanIds(root); } catch (_) { return; }

  assert.ok(scan.byDefId.size > 700, "should find the existing cards by def_id");
  assert.ok(scan.max >= scan.byDefId.size, "max id is at least the card count");

  // Every def_id maps to exactly one id, and no two cards share one.
  const ids = [...scan.byDefId.values()];
  assert.equal(new Set(ids).size, ids.length, "two cards share an id");
});

test("highestId still reports the ceiling", () => {
  const root = process.env.ALPHARUNE_ROOT || "../chorlick/alpharune";
  try {
    assert.equal(G.highestId(root), G.scanIds(root).max);
  } catch (_) { /* no checkout */ }
});

/* Overwrite protection. The hand-written cards are untracked files inside the
 * engine checkout, so a re-run of the generator would have replaced all four
 * with data-only stubs — silently, since the build still succeeds and the
 * cards simply stop doing anything. */
test("generated output carries the marker the generator looks for", () => {
  const src = G.generate(AKALI, 900);
  assert.match(src, /GENERATED by coach\/gen-cards\.js/,
    "without this marker the generator cannot tell its own output from a hand-written card");
});

test("a hand-written card in this repo has no generated marker", () => {
  const fs2 = require("fs");
  const path2 = require("path");
  const dir = path2.join(__dirname, "..", "engine", "cards");
  if (!fs2.existsSync(dir)) return;
  const cards = fs2.readdirSync(dir).filter((f) => f.endsWith(".cpp"));
  assert.ok(cards.length > 0, "engine/cards should hold the hand-written implementations");
  for (const f of cards) {
    const text = fs2.readFileSync(path2.join(dir, f), "utf8");
    assert.doesNotMatch(text, /GENERATED by coach\/gen-cards\.js/,
      `${f} carries the generated marker — a regeneration would overwrite it`);
  }
});

/* The type error that shipped: LocationId is variant<BaseLocation,
 * BattlefieldLocation>, and get_if<BattlefieldId> asks for a type the variant
 * does not hold. It compiled in no sense at all, and was reported as working
 * because the build was still running when its output was grepped. */
test("hand-written cards do not ask a variant for a type it cannot hold", () => {
  const fs2 = require("fs");
  const path2 = require("path");
  const dir = path2.join(__dirname, "..", "engine", "cards");
  if (!fs2.existsSync(dir)) return;
  for (const f of fs2.readdirSync(dir).filter((x) => x.endsWith(".cpp"))) {
    const text = fs2.readFileSync(path2.join(dir, f), "utf8");
    assert.doesNotMatch(text, /get_if<BattlefieldId>/,
      `${f}: LocationId holds BattlefieldLocation, not BattlefieldId`);
  }
});

/* The install script picks a directory from the card's declared type. An
 * unanchored match reads whatever CardType the card's LOGIC mentions first —
 * Decree of Unity tests `obj.card_type == CardType::Gear` while enumerating
 * targets, and got installed as gear, registering the same card id twice from
 * two directories. */
test("every hand-written card declares its type unambiguously", () => {
  const fs2 = require("fs");
  const path2 = require("path");
  const dir = path2.join(__dirname, "..", "engine", "cards");
  if (!fs2.existsSync(dir)) return;

  for (const f of fs2.readdirSync(dir).filter((x) => x.endsWith(".cpp"))) {
    const text = fs2.readFileSync(path2.join(dir, f), "utf8");
    const decls = text.match(/d\.card_type = CardType::\w+/g) || [];
    assert.equal(decls.length, 1, `${f}: expected exactly one d.card_type declaration`);
  }
});

test("a card id is registered exactly once across the engine's card tree", () => {
  const fs2 = require("fs");
  const path2 = require("path");
  const root = process.env.ALPHARUNE_ROOT ||
    path2.join(__dirname, "..", "..", "chorlick", "alpharune");
  const cardsDir = path2.join(root, "src", "cards");
  if (!fs2.existsSync(cardsDir)) return;

  const seen = new Map();
  for (const sub of fs2.readdirSync(cardsDir)) {
    const d = path2.join(cardsDir, sub);
    if (!fs2.statSync(d).isDirectory()) continue;
    for (const f of fs2.readdirSync(d).filter((x) => x.endsWith(".cpp"))) {
      const text = fs2.readFileSync(path2.join(d, f), "utf8");
      for (const m of text.matchAll(/void register_card_(\d+)\(CardRegistry&\s*\w*\)\s*\{/g)) {
        const id = m[1];
        if (seen.has(id)) {
          assert.fail(`card ${id} registered in both ${seen.get(id)} and ${sub}/${f}`);
        }
        seen.set(id, `${sub}/${f}`);
      }
    }
  }
  assert.ok(seen.size > 900, `expected the full registry, saw ${seen.size}`);
});

/* Reprints. A card printed again in a later set is a second entry with its
 * own id and its own file, so implementing one leaves the other a stub — and
 * which one a board resolves to depends on the printing that was played.
 * Draven, Showboat found this the slow way. */
test("no card has one printing working and another not", () => {
  let index, files;
  try {
    index = require("../coach/alpharune.js").loadIndex();
    files = require("../coach/fidelity.js").scanCardFiles();
  } catch (_) { return; }
  if (!files.size) return;

  const { mismatched } = require("../coach/port-reprint.js");
  const bad = mismatched(index, files);
  assert.deepEqual(
    bad.map((b) => `${b.name}: ${b.from.public_code} works, ${b.to.map((t) => t.public_code)} does not`),
    [],
    "run: node coach/port-reprint.js --write"
  );
});

test("porting keeps each printing's own CardDef and class name", () => {
  const { split } = require("../coach/port-reprint.js");
  const src = [
    '#include "cards/card.h"',
    "namespace riftbound {",
    "class AlphaCard : public UnitCard {",
    "public:",
    "    void onPlay(CardContext& ctx) override {}",
    "    const CardDef def_ = [] {",
    "        CardDef d;",
    "        d.id = 1;",
    "    }();",
    "};",
  ].join("\n");
  const parts = split(src);
  assert.ok(parts, "a card file should split into head / class / CardDef");
  assert.match(parts.cls, /onPlay/, "behaviour belongs to the class half");
  assert.match(parts.def, /d\.id = 1;/, "the id belongs to the CardDef half");
  assert.doesNotMatch(parts.cls, /d\.id/, "the id must not travel with the behaviour");
});

/* A keyword printed after an [Empowered] gate is not one the card has.
 *
 * "[Empowered][>] I have [Assault 3]" grants Assault while a latch is set,
 * and the latch starts clear. Put on the CardDef it is unconditional, so an
 * un-Empowered Shadow Fiend attacks as a 5 for [2][Fury] — strictly better
 * than the printed card. Thirteen VEN cards were generated that way, and
 * none of them errored; they were simply better than they read, in the
 * direction a search finds first. */
test("keywords gated on [Empowered] do not reach the CardDef", () => {
  const { keywordsOf } = require("../coach/gen-cards.js");

  assert.deepStrictEqual(
    keywordsOf({
      description:
        "[Empower] :rb_energy_2::rb_rune_fury: (Empower me. Use only if not " +
        "Empowered.)[Empowered][>] I have [Assault 3]. (+3 :rb_might: while " +
        "I'm an attacker.)",
    }),
    [],
    "Shadow Fiend has no Assault until it is Empowered"
  );

  assert.deepStrictEqual(
    keywordsOf({
      description:
        "[Empower] :rb_energy_3: (Empower me.)[Empowered][>] I have " +
        "[Deflect] and [Shield 3].",
    }),
    [],
    "both of Serene Ascetic's keywords are behind the gate"
  );
});

test("a keyword printed before the gate is still the card's own", () => {
  const { keywordsOf } = require("../coach/gen-cards.js");
  // Steel Paws prints [Deflect] outright and only its +7 Might is gated.
  // Dropping everything after the first [Empowered] would lose the Deflect,
  // which is the half of the card you play on turn one.
  assert.deepStrictEqual(
    keywordsOf({
      description:
        "[Deflect] (Opponents must pay :rb_rune_rainbow: to choose me.)" +
        "[Empower] :rb_energy_7: (Empower me.)[Empowered][>] I have +7 :rb_might:.",
    }),
    ["Deflect"]
  );
});

/* The check that would have caught all thirteen. Scans the engine checkout
 * rather than the generator, so a card edited by hand is covered too. */
test("no card in the engine carries a keyword its text gates on [Empowered]", () => {
  const fs = require("fs");
  const path = require("path");
  const root =
    process.env.ALPHARUNE_ROOT ||
    path.join(__dirname, "..", "..", "chorlick", "alpharune");
  const dir = path.join(root, "src", "cards");
  if (!fs.existsSync(dir)) {
    console.log("# SKIP no alpharune checkout — this check needs one");
    return;
  }

  const KW = ["Assault", "Shield", "Deflect", "Tank", "Ghost", "Vision",
              "Deathknell", "Legion", "Accelerate", "Ambush", "Ganking"];
  const offenders = [];
  for (const sub of fs.readdirSync(dir)) {
    const d = path.join(dir, sub);
    if (!fs.statSync(d).isDirectory()) continue;
    for (const f of fs.readdirSync(d)) {
      if (!/^\d+_.*\.cpp$/.test(f)) continue;
      const src = fs.readFileSync(path.join(d, f), "utf8");
      const abil = (/d\.ability_text = R"RB\(([\s\S]*?)\)RB";/.exec(src) || [])[1];
      if (!abil) continue;
      const bare = abil.replace(/\([^()]*\)/g, "");
      const at = bare.search(/\[Empowered\]/);
      if (at < 0) continue;
      const after = bare.slice(at);
      for (const kw of KW) {
        if (!new RegExp("\\[" + kw).test(after)) continue;
        if (new RegExp("\\[" + kw).test(bare.slice(0, at))) continue; // also ungated
        if (new RegExp("d\\.keywords\\.set\\(Keyword::" + kw + "\\)").test(src)) {
          offenders.push(`${sub}/${f} [${kw}]`);
        }
      }
    }
  }
  assert.deepStrictEqual(
    offenders,
    [],
    "these cards claim a keyword their text only grants while Empowered:\n  " +
      offenders.join("\n  ")
  );
});
