#!/usr/bin/env bash
# Regenerate engine/patches/*.patch from the alpharune checkout, and refuse to
# install them unless they actually apply to a pristine tree.
#
# The old patch set was generated by hand, one `git diff <files>` per feature,
# from a tree that already carried the earlier features. Two of them touched
# game_engine.cpp and so each contained the other's hunks; applying them in
# order failed on the second. Nothing caught it, because nothing ever tried
# them against a clean checkout — which is the only way to know.
#
# So this script always does that: generate, apply to a throwaway worktree at
# upstream HEAD, and only then overwrite what is in engine/patches/.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="${ALPHARUNE_ROOT:-$(cd "$HERE/../chorlick/alpharune" 2>/dev/null && pwd || true)}"
WORK="${TMPDIR:-/tmp}/regen-engine-patches.$$"

[ -n "$ROOT" ] && [ -d "$ROOT/src" ] || {
  echo "No alpharune checkout found. Set ALPHARUNE_ROOT." >&2; exit 2; }

# Every non-card engine file this project modifies.
#
# This list was hand-maintained and went stale, and the way it failed is the
# point: eight files were missing — game_object.h with the new fields,
# game_engine.h with the new declarations, card.cpp with pickTargets itself —
# so the patch set APPLIED cleanly to a pristine checkout and then would not
# compile. The apply-check below was a proxy for "this works on someone
# else's machine" and the proxy was wrong. A fresh clone got 20+ errors of
# the form "GameObject has no member named damage_prevention_pool".
#
# So it is derived now, not listed: everything modified outside src/cards/'s
# per-card files, which patches 02 and 03 and install.sh own. Adding an
# engine file can no longer forget to add it here.
mapfile -t CORE < <(cd "$ROOT" && git diff --name-only -- src/ \
  | grep -vE '^src/cards/(battlefields|legends|spells|units)/' \
  | grep -v '^src/cards/cards_init\.cpp$')

stage="$WORK/staged"
mkdir -p "$stage"
# `git diff` does not see an untracked file, and a NEW test file is exactly
# what a new mechanic adds — tests/cards/test_flow.cpp was silently left out
# of the patch the first time this ran. `add -N` records intent-to-add so the
# diff includes it; the index is put back afterwards either way.
git -C "$ROOT" add -N -- "${CORE[@]}" tests/ >/dev/null 2>&1 || true
(cd "$ROOT" && git diff -- "${CORE[@]}") > "$stage/01-engine-core.patch"
(cd "$ROOT" && git diff -- tests/)      > "$stage/02-engine-tests.patch"
git -C "$ROOT" reset -q -- "${CORE[@]}" tests/ >/dev/null 2>&1 || true

# ── 03: corrections to UPSTREAM card data ───────────────────────────────
#
# A third patch exists because a third kind of change exists, and it had
# nowhere to go. The card tree holds files from three sources:
#
#   1. generated from state/sets/*.json by coach/gen-cards.js
#   2. hand-written here, in engine/cards/, installed by its install.sh
#   3. upstream alpharune's own, which this repo does not otherwise touch
#
# Only (3) needs a patch — (1) is reproduced by re-running the generator and
# (2) by re-running install.sh, so patching them would apply the same change
# twice. Fourteen upstream cards carried a keyword their text only GRANTS to
# something else (Yuumi's [Tank], Gem Jammer's [Ganking], Lord Broadmane's
# [Assault]); those corrections are real changes to files nothing else here
# reproduces, and without this patch a fresh checkout would silently lose
# them.
#
# The exclusions are computed, not listed, so the boundary cannot drift: a
# file is (1) if it carries the generator's marker and (2) if engine/cards/
# holds a file with the same basename.
mapfile -t CHANGED < <(cd "$ROOT" && git diff --name-only -- src/cards/)
UPSTREAM=()
for f in "${CHANGED[@]:-}"; do
  [ -n "$f" ] || continue
  # src/cards/ holds card.h and card_helpers.h too, and those are patch 01's.
  # Without this the same hunks land in two patches and the second refuses.
  skip=
  for c in "${CORE[@]}"; do [ "$f" = "$c" ] && skip=1; done
  [ -n "$skip" ] && continue
  base="$(basename "$f")"
  # `if` rather than `x && continue`: under `set -e` a trailing AND-list
  # that fails exits the script, so the no-match case would abort the run.
  if [ -e "$HERE/engine/cards/$base" ]; then continue; fi                    # (2)
  if grep -q "GENERATED by coach/gen-cards.js" "$ROOT/$f"; then continue; fi # (1)
  UPSTREAM+=("$f")
done
if [ "${#UPSTREAM[@]}" -gt 0 ]; then
  (cd "$ROOT" && git diff -- "${UPSTREAM[@]}") > "$stage/03-card-data.patch"
else
  : > "$stage/03-card-data.patch"
fi

for p in "$stage"/*.patch; do
  [ -s "$p" ] || { echo "empty: $(basename "$p") — nothing to patch?" >&2; }
done

# Pristine worktree at upstream HEAD. Not a copy of the checkout: the point is
# a tree with none of our changes in it.
tree="$WORK/pristine"
cleanup() { git -C "$ROOT" worktree remove --force "$tree" >/dev/null 2>&1 || true
            rm -rf "$WORK"; }
trap cleanup EXIT
git -C "$ROOT" worktree add --detach "$tree" HEAD >/dev/null 2>&1

for p in "$stage"/*.patch; do
  [ -s "$p" ] || continue
  if ! git -C "$tree" apply "$p"; then
    echo "REFUSING: $(basename "$p") does not apply to a pristine checkout." >&2
    echo "The patches in engine/patches/ are unchanged." >&2
    exit 1
  fi
done

# Applying is not compiling, and that distinction cost a fresh clone a build.
#
# The apply-check above only proves the hunks land. A patch set can be
# INCOMPLETE and still apply perfectly: ship game_engine.cpp without
# game_object.h and every hunk goes in, then the compiler asks what
# `damage_prevention_pool` is. That is exactly what happened, and it happened
# on somebody else's machine, which is the only place it could happen.
#
# So the patched tree is now compiled — not linked, not tested, just parsed
# and type-checked, which is enough to catch a missing declaration and takes
# seconds rather than half an hour.
GEN="$ROOT/build/generated"
JSON="$ROOT/build/_deps/open_spiel-src/open_spiel/json/include"
if [ -d "$GEN" ]; then
  echo "compile-checking the patched tree ..."
  fail=0
  while IFS= read -r f; do
    case "$f" in *.cpp) ;; *) continue ;; esac
    [ -f "$tree/$f" ] || continue
    if ! (cd "$tree" && g++ -fsyntax-only -std=gnu++20 \
            -I"$GEN" -Isrc -I"$JSON" "$f" 2>&1 | head -5); then :; fi
    if ! (cd "$tree" && g++ -fsyntax-only -std=gnu++20 \
            -I"$GEN" -Isrc -I"$JSON" "$f" >/dev/null 2>&1); then
      echo "  FAILS TO COMPILE: $f" >&2; fail=1
    fi
  done < <(printf '%s\n' "${CORE[@]}")
  if [ "$fail" -ne 0 ]; then
    echo "REFUSING: the patch set applies but does not compile." >&2
    echo "The patches in engine/patches/ are unchanged." >&2
    exit 1
  fi
  echo "  compiles"
else
  # Skip loudly. Unverified is not the same as passing.
  echo "SKIPPED the compile check — no $GEN (build the engine once first)." >&2
fi

cp "$stage"/*.patch "$HERE/engine/patches/"
echo "regenerated and verified against a pristine $ROOT HEAD:"
wc -l "$HERE"/engine/patches/*.patch
