#!/usr/bin/env bash
# Regenerate engine/patches/*.patch from the alpharune checkout, and refuse to
# install them unless they actually apply to a pristine tree.
#
# The old patch set was generated by hand, one `git diff <files>` per feature,
# from a tree that already carried the earlier features. Two of them touched
# game_engine.cpp and so each contained the other's hunks; applying them in
# order failed on the second. Nothing caught it, because nothing ever tried
# them against a clean checkout — which is the only way to know.
#
# So this script always does that: generate, apply to a throwaway worktree at
# upstream HEAD, and only then overwrite what is in engine/patches/.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="${ALPHARUNE_ROOT:-$(cd "$HERE/../chorlick/alpharune" 2>/dev/null && pwd || true)}"
WORK="${TMPDIR:-/tmp}/regen-engine-patches.$$"

[ -n "$ROOT" ] && [ -d "$ROOT/src" ] || {
  echo "No alpharune checkout found. Set ALPHARUNE_ROOT." >&2; exit 2; }

CORE=(src/cards/card.h src/cards/card_helpers.h
      src/engine/effect_executor.h src/engine/effect_executor.cpp
      src/core/game_state.h src/engine/game_engine.cpp)

stage="$WORK/staged"
mkdir -p "$stage"
# `git diff` does not see an untracked file, and a NEW test file is exactly
# what a new mechanic adds — tests/cards/test_flow.cpp was silently left out
# of the patch the first time this ran. `add -N` records intent-to-add so the
# diff includes it; the index is put back afterwards either way.
git -C "$ROOT" add -N -- "${CORE[@]}" tests/ >/dev/null 2>&1 || true
(cd "$ROOT" && git diff -- "${CORE[@]}") > "$stage/01-engine-core.patch"
(cd "$ROOT" && git diff -- tests/)      > "$stage/02-engine-tests.patch"
git -C "$ROOT" reset -q -- "${CORE[@]}" tests/ >/dev/null 2>&1 || true

# ── 03: corrections to UPSTREAM card data ───────────────────────────────
#
# A third patch exists because a third kind of change exists, and it had
# nowhere to go. The card tree holds files from three sources:
#
#   1. generated from state/sets/*.json by coach/gen-cards.js
#   2. hand-written here, in engine/cards/, installed by its install.sh
#   3. upstream alpharune's own, which this repo does not otherwise touch
#
# Only (3) needs a patch — (1) is reproduced by re-running the generator and
# (2) by re-running install.sh, so patching them would apply the same change
# twice. Fourteen upstream cards carried a keyword their text only GRANTS to
# something else (Yuumi's [Tank], Gem Jammer's [Ganking], Lord Broadmane's
# [Assault]); those corrections are real changes to files nothing else here
# reproduces, and without this patch a fresh checkout would silently lose
# them.
#
# The exclusions are computed, not listed, so the boundary cannot drift: a
# file is (1) if it carries the generator's marker and (2) if engine/cards/
# holds a file with the same basename.
mapfile -t CHANGED < <(cd "$ROOT" && git diff --name-only -- src/cards/)
UPSTREAM=()
for f in "${CHANGED[@]:-}"; do
  [ -n "$f" ] || continue
  # src/cards/ holds card.h and card_helpers.h too, and those are patch 01's.
  # Without this the same hunks land in two patches and the second refuses.
  skip=
  for c in "${CORE[@]}"; do [ "$f" = "$c" ] && skip=1; done
  [ -n "$skip" ] && continue
  base="$(basename "$f")"
  # `if` rather than `x && continue`: under `set -e` a trailing AND-list
  # that fails exits the script, so the no-match case would abort the run.
  if [ -e "$HERE/engine/cards/$base" ]; then continue; fi                    # (2)
  if grep -q "GENERATED by coach/gen-cards.js" "$ROOT/$f"; then continue; fi # (1)
  UPSTREAM+=("$f")
done
if [ "${#UPSTREAM[@]}" -gt 0 ]; then
  (cd "$ROOT" && git diff -- "${UPSTREAM[@]}") > "$stage/03-card-data.patch"
else
  : > "$stage/03-card-data.patch"
fi

for p in "$stage"/*.patch; do
  [ -s "$p" ] || { echo "empty: $(basename "$p") — nothing to patch?" >&2; }
done

# Pristine worktree at upstream HEAD. Not a copy of the checkout: the point is
# a tree with none of our changes in it.
tree="$WORK/pristine"
cleanup() { git -C "$ROOT" worktree remove --force "$tree" >/dev/null 2>&1 || true
            rm -rf "$WORK"; }
trap cleanup EXIT
git -C "$ROOT" worktree add --detach "$tree" HEAD >/dev/null 2>&1

for p in "$stage"/*.patch; do
  [ -s "$p" ] || continue
  if ! git -C "$tree" apply "$p"; then
    echo "REFUSING: $(basename "$p") does not apply to a pristine checkout." >&2
    echo "The patches in engine/patches/ are unchanged." >&2
    exit 1
  fi
done

cp "$stage"/*.patch "$HERE/engine/patches/"
echo "regenerated and verified against a pristine $ROOT HEAD:"
wc -l "$HERE"/engine/patches/*.patch
