#!/usr/bin/env bash
# Regenerate engine/patches/*.patch from the alpharune checkout, and refuse to
# install them unless they actually apply to a pristine tree.
#
# The old patch set was generated by hand, one `git diff <files>` per feature,
# from a tree that already carried the earlier features. Two of them touched
# game_engine.cpp and so each contained the other's hunks; applying them in
# order failed on the second. Nothing caught it, because nothing ever tried
# them against a clean checkout — which is the only way to know.
#
# So this script always does that: generate, apply to a throwaway worktree at
# upstream HEAD, and only then overwrite what is in engine/patches/.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="${ALPHARUNE_ROOT:-$(cd "$HERE/../chorlick/alpharune" 2>/dev/null && pwd || true)}"
WORK="${TMPDIR:-/tmp}/regen-engine-patches.$$"

[ -n "$ROOT" ] && [ -d "$ROOT/src" ] || {
  echo "No alpharune checkout found. Set ALPHARUNE_ROOT." >&2; exit 2; }

CORE=(src/cards/card.h src/cards/card_helpers.h
      src/engine/effect_executor.h src/engine/effect_executor.cpp
      src/core/game_state.h src/engine/game_engine.cpp)

stage="$WORK/staged"
mkdir -p "$stage"
(cd "$ROOT" && git diff -- "${CORE[@]}") > "$stage/01-engine-core.patch"
(cd "$ROOT" && git diff -- tests/)      > "$stage/02-engine-tests.patch"

for p in "$stage"/*.patch; do
  [ -s "$p" ] || { echo "empty: $(basename "$p") — nothing to patch?" >&2; }
done

# Pristine worktree at upstream HEAD. Not a copy of the checkout: the point is
# a tree with none of our changes in it.
tree="$WORK/pristine"
cleanup() { git -C "$ROOT" worktree remove --force "$tree" >/dev/null 2>&1 || true
            rm -rf "$WORK"; }
trap cleanup EXIT
git -C "$ROOT" worktree add --detach "$tree" HEAD >/dev/null 2>&1

for p in "$stage"/*.patch; do
  [ -s "$p" ] || continue
  if ! git -C "$tree" apply "$p"; then
    echo "REFUSING: $(basename "$p") does not apply to a pristine checkout." >&2
    echo "The patches in engine/patches/ are unchanged." >&2
    exit 1
  fi
done

cp "$stage"/*.patch "$HERE/engine/patches/"
echo "regenerated and verified against a pristine $ROOT HEAD:"
wc -l "$HERE"/engine/patches/*.patch
